name: Siirto
description: Lisää siirto-ilmoitus. Muista lisätä otsikko ja oikealle projekti-osioon "Versionvaihto".
labels: [bug]
body:
- type: textarea
  attributes:
    label: Siirrettävä ominaisuus
    description: Kerro mahdollisimman tarkasti, mikä ominaisuus siirretään. Asiakastietoja ei saa lisätä tikettiin, linkki asiakastietoon riittää.
  validations:
    required: false
